module.exports = {
  INTAKE_PARSER_PROMPT: require('./intake-parser'),
  ATTENDING_PROMPT: require('./attending'),
  CARDIOLOGIST_PROMPT: require('./cardiologist'),
  PULMONOLOGIST_PROMPT: require('./pulmonologist'),
  NEPHROLOGIST_PROMPT: require('./nephrologist'),
  HEPATOLOGIST_PROMPT: require('./hepatologist'),
  HEMATOLOGIST_PROMPT: require('./hematologist'),
  ID_SPECIALIST_PROMPT: require('./id-specialist'),
  RADIOLOGIST_PROMPT: require('./radiologist'),
  PHARMACIST_PROMPT: require('./pharmacist'),
  ENDOCRINOLOGIST_PROMPT: require('./endocrinologist'),
  NEUROLOGIST_PROMPT: require('./neurologist'),
  INTENSIVIST_PROMPT: require('./intensivist'),
  ONCOLOGIST_PROMPT: require('./oncologist'),
  PSYCHIATRIST_PROMPT: require('./psychiatrist'),
  TOXICOLOGIST_PROMPT: require('./toxicologist'),
  PALLIATIVE_PROMPT: require('./palliative'),
};
